name: glados-auto-checkin

on:
  workflow_dispatch:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  schedule:
    - cron: 30 2,15 * * *
      # https://tool.lu/crontab/
      # https://datetime360.com/cn/utc-cst-china-time/
  #watch:
  #    types: started   

jobs:
  checkin:
    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id
    # https://p3terx.com/archives/github-actions-manual-trigger.html
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v4
      #      - name: install requirements
      #        run: |
      #          python -m pip install --upgrade pip
      #          pip3 install -r requirements.txt
      #          # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Checkin
        run: |
          python3 ./glados/main.py
        env:
          GLADOS_COOKIE: ${{ secrets.GLADOS_COOKIE }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
      - uses: gautamkrishnar/keepalive-workflow@master # using the workflow with default settings
